.github/workflows/discord-pr-merged-notify.yml

- #13 
- curl 명령어 안의 디스코드 알림 메세지를 heredoc 형식으로 다시 변경
- JSON 포맷이 깨지는 오류로 인하여, 디스코드 알림 메세지를 heredoc 형식으로 다시 변경
- PR 관련 기능을 테스트하기 위해 PR Merge 중입니다.
- x
- x

fix: content 안의 메세지를 heredoc 형식으로 재변경

---

.github/workflows/discord-pr-merged-notify.yml

- #14 
- 디스코드 알림 메시지의 형식 변경
- 디스코드 알림으로 요청오는데 성공하였으나, 텍스트의 마크다운 형식이 깨져서 옴
- Discord 웹훅의 `embeds`를 이용하여 마크다운 형식 유지 시도
- x
- x
- PR 메세지 원본
- 디스코드에 온 알림

fix: 디스코드 메세지에서 PR 본문에 대한 형식 변경

---

.github/workflows/discord-pr-merged-notify.yml

- #15 
- PR 메세지의 description을 code block으로 처리
- curl 명령을 보내는 스크립트에서, 마크다운 문법으로 작성된 PR 메세지의 description을 제대로 처리하지 못함
- 그래서 description을 통째로 code block으로 감쌈
- PR 관련 기능을 테스트하기 위해 PR Merge 중입니다.
- x
- x
- x

fix: PR 메세지의 description을 code block으로 처리

---

backend/workflows/cd-backend.yml

- ㅌ
- 디스코드 봇 url을 Github Secrets에서 가져오게 변경
- 디스코드 봇 url을 Github Secrets에서 가져오게 변경

fix: 디스코드 봇 url을 Github Secrets에서 가져오게 변경

---

terraform/environments/shared/main.tf

[Sprint #4 - CL] - terraform-ec2 [#221](https://github.com/100-hours-a-week/2-hertz-wiki/issues/221)
- NatGateway가 private subnet에 위치하여 인터넷이 안되는 이슈가 있었다.
- public subnet으로 변경
- NatGateWay는 public에 위치하여야 eip를 통한 인터넷 통신이 가능하다.

fix: nat-게이트웨이 퍼블릭 서브넷으로 변경

---

backend/workflows/cicd-backend.yml
frontend/workflows/cicd-frontend.yml

- cd 실패 시 rollback으로 넘어가지 않는 오류 수정
- rollback job 트리거에 조건문이 잘못되어 rollback이 수행되지 않음.
- rollback job의 트리거로 `always() && needs.backend-cd.result != 'success'`를 설정

fix: cd 실패 시 rollback으로 넘어가지 않는 오류 수정

---

terraform/gcp/environments/shared/main.tf

- 네트워크 타겟 태그 이름이 맞지 않았던 것을 수정
```
module "backend" {
source                = "../../modules/compute"
name                  = "backend"
machine_type          = "e2-medium"
zone                  = "asia-east1-b"
image                 = "ubuntu-os-cloud/ubuntu-2204-lts"
disk_size_gb          = 10
tags                  = ["allow-vpn-ssh"]
```
```
{
name          = "ssh-from-vpn"
env           = var.env
direction     = "INGRESS"
priority      = 1003
protocol      = "tcp"
ports         = ["22"]
source_ranges = var.vpn_client_cidr_blocks 
target_tags   = ["allow-vpn-ssh"]
description   = "Allow SSH from VPN clients"
}
```

fix: 네트워크 타겟 태그 수정

---

terraform/gcp/environments/shared/main.tf
terraform/gcp/environments/shared/scripts/install-openvpn.sh.tpl
terraform/gcp/environments/shared/variables.tf

- private, nat 서브넷 대역을 라우팅 하도록 수정
```
VPN_PRIVATE_NETWORKS="${vpn_private_networks:-""}"
IFS=',' read -ra SUBNETS <<< "$VPN_PRIVATE_NETWORKS"
echo "[INFO] OpenVPN 라우팅에 아래 CIDR들을 추가합니다:"
for i in "${!SUBNETS[@]}"; do
CIDR="${SUBNETS[$i]}"
if [[ -n "$CIDR" ]]; then
echo "  - $CIDR"
sudo /usr/local/openvpn_as/scripts/sacli --key "vpn.server.routing.private_network.${i}" --value "$CIDR" ConfigPut
fi
done
```

fix: vpn 라우팅 주소 추가

---

terraform/gcp/environments/shared/main.tf
terraform/gcp/modules/compute/main.tf
terraform/gcp/modules/compute/output.tf
terraform/gcp/modules/firewall/main.tf
terraform/gcp/modules/firewall/variables.tf
terraform/gcp/modules/network/main.tf
terraform/gcp/modules/network/variables.tf

[Sprint #5 - CL] - gcp-openvpn
[#249](https://github.com/100-hours-a-week/2-hertz-wiki/issues/249)
- openvpn 서버에 고정 IP를 생성하고 destroy_prevent를 추가
- openvpn은 destroy 하지 않고 수동으로 중지하여 기존의 세팅이 초기화 되는 것을 방지 하는 운영을 위해

feat: 고정 IP 추가 , destroy_prevent 추가

---

terraform/gcp/environments/develop/main.tf
terraform/gcp/environments/develop/variable.tf
terraform/gcp/modules/external-https-lb/main.tf
terraform/gcp/modules/internal-http-lb/main.tf
terraform/gcp/modules/internal-http-lb/variables.tf

-  proxy only subnet 추가
- external alb url-map matches 수정
```
resource "google_compute_subnetwork" "ilb_proxy_subnet" {
name          = "${var.vpc_name}-ilb-proxy-subnet"
ip_cidr_range = var.proxy_subnet_cidr #"10.10.31.0/28"             # 원하는 CIDR(내부 IP 풀)
region        = var.region                 # 예: asia-east1
network       = local.vpc_self_link          # VPC self_link
purpose                         = "INTERNAL_HTTPS_LOAD_BALANCER"
private_ip_google_access        = true    # 필요 시 활성화
}
```

fix: proxy only subnet, external alb 수정

---

terraform/gcp/modules/external-https-lb/output.tf

hotfix
```
output "forwarding_rule_ip" {
description = "외부 HTTPS LB 공인 IP"
value       = google_compute_global_forwarding_rule.https_fr.ip_address
}
```

hotfix: external_output 수정

---

terraform/gcp/environments/develop/main.tf

hotfix  
```
named_port {
name = "http"
port = 8080
}
```

hotfix: ig에 namePort 추가

---

.gitignore
terraform/gcp/environments/prod/variable.tf
terraform/gcp/modules/mig-asg/main.tf

- 헬스체크 시간(300 -> 420초) 및 blue asg 인스턴스 수(min 0, max 0) 변경
- 인스턴스 초기 세팅 시간이 300초로 부족하여 대기시간 증가
- 초기 apply 시, blue asg의 인스턴스의 필요성이 없기 때문에 min 0, max 0으로 변경하여 미생성
- 헬스체크 시간 변경: 300 -> 420초
- blue asg 인스턴스 수 변경: min 1, max 2 -> min 0, max 0

fix: 헬스체크 시간(300 -> 420초) 및 blue asg 인스턴스 수(min 0, max 0) 변경

---

terraform/gcp/environments/develop/main.tf
terraform/gcp/environments/develop/scripts/backend-install.sh.tpl
terraform/gcp/environments/develop/scripts/db-install.sh.tpl
terraform/gcp/environments/develop/scripts/vm-install.sh.tpl
terraform/gcp/environments/develop/variable.tf
terraform/gcp/environments/prod/main.tf
terraform/gcp/environments/prod/scripts/backend-install.sh.tpl
terraform/gcp/environments/prod/scripts/db-install.sh.tpl

- DB 인스턴스에 백엔드 서버가 scp 접속 가능하도록 수정 
- mount point 수정
- private subnet에 위치한 db 세팅의 유연성을 위해 백엔드 서버에서 basiton 서버처럼 서버 세팅할 수 있도록 설정하였습니다.
- mysql-data 디렉토리가 비어 있거나 db 세팅 이외의 폴더나 파일이 들어가면 오류가 나기 때문에 세팅과 볼륨을 분리하였습니다.
- 기존 `/mnt/mysql-data`  변경 후 ` /mnt/tmp/mysql-data`   /mnt/tmp에는 db 세팅 파일

fix: DB 인스턴스에 백엔드 서버가 scp 접속 가능하도록 수정, mount point 수정

---

terraform/gcp/environments/prod/output.tf

-  가동중인 ASG를 구분하는 코드 변경(active_deployment 값 -> instance_count의 max값)
- active_deployment는 local 변수로만 사용되고, 리소스에 사용되지 않아, active_deployment값이 변해도 apply 시 변경하지 않는 문제가 있어서 로직을 변경
- 기존: active_deployment 값이 blue인지 green인지에 따라 target 그룹 지정
- 변경: blue_instance_count 또는 green_instance_count의 max 값이 0인 곳이 어디냐에 따라 target 그룹 지정

fix: 가동중인 ASG를 구분하는 코드 변경(active_deployment 값 -> instance_count의 max값)

---

terraform/gcp/environments/prod/main.tf
terraform/gcp/modules/target-group/main.tf
terraform/gcp/modules/target-group/variables.tf

- apply 시 traffic_weight_bluetraffic_weight_green 값의 변경을 적용하기 위해 리소스에 해당 값을 적용
- `description` 속성을 추가해 traffic_weight_blue/traffic_weight_green 값이 반영되게 하여, apply 시 인식이 되게 변경
```
module "frontend_tg" {
source       = "../../modules/target-group"
✅ description  = "Traffic: blue ${var.traffic_weight_blue}% / green ${var.traffic_weight_green}%"
name         = "${var.env}-frontend-tg"
health_check = local.hc_frontend
backends = [
{
instance_group  = module.frontend_asg_blue.instance_group
weight          = local.normalized_blue_weight
balancing_mode  = "UTILIZATION"
capacity_scaler = 1.0
},
{
instance_group  = module.frontend_asg_green.instance_group
weight          = local.normalized_green_weight
balancing_mode  = "UTILIZATION"
capacity_scaler = 1.0
}
] …
```

fix: apply 시 traffic_weight_bluetraffic_weight_green 값의 변경을 적용하기 위해 리소스에 해당 값을 적용

---

terraform/gcp/environments/prod/main.tf
terraform/gcp/environments/prod/output.tf
terraform/gcp/environments/prod/variable.tf
terraform/gcp/modules/target-group/variables.tf

- ASG 트래픽 받는 용량 조절을 weight -> capacity_scaler 속성으로 변경
- 부하분산의 backend 서비스에 weight 라는 속성이 없는 것으로 확인됨
- capacity_scaler 속성을 통해서 ASG의 backend에 꽂히는 트래픽 양을 조절할 수 있는 것으로 확인되어, 해당 속성에 traffic_weight_blue/traffic_weight_green을 연결

fix: ASG 트래픽 받는 용량 조절을 weight -> capacity_scaler 속성으로 변경

---

terraform/gcp/modules/mig-asg/main.tf
terraform/gcp/modules/target-group/variables.tf

- ASG 초기세팅 시간 속성으로 잘못된 속성을 사용하여 수정(cooldown_period 추가)
- `google_compute_region_instance_group_manager` 리소스의 `initial_delay_sec` 속성: 헬스체크 결과 무시 기간
-  `google_compute_region_autoscaler` 리소스의 `cooldown_period` 속성: ASG에서 인스턴스가 새로 올라왔을 때, 사용량 등에 대한 데이터를 수집하지 않도록 하는 기간

fix: ASG 초기세팅 시간 속성으로 잘못된 속성을 사용하여 수정(cooldown_period 추가)

---

terraform/gcp/environments/shared/main.tf
terraform/gcp/modules/target-group/variables.tf

- DB 디스크 스냅샷 일정 추가
- 스냅샷 정책(snapshot_policy) 추가
- \+ 디스크 이름에 suffix 추가(-dev, -prod)
**백업 정책**
> 대상: DB VM에 연결된 디스크에 대한 스냅샷
> 백업 주기: 매일 04시, 하루 3회, 8시간 간격 자동 실행
> 백업 방식: GCP의 증분 스냅샷 기능 활용
> 보존 기간: 30일 유지 및 자동 삭제

feat: DB 디스크 스냅샷 일정 추가

---

backend/workflows/docker-cicd-backend.yml
helm/nextjs-fe/values-dev.yaml
helm/nextjs-fe/values-prod.yaml
terraform/gcp/modules/external-https-lb/main.tf

- external-https-lb 모듈을 수정하여 HTTP에서 HTTPS로의 리디렉션을 구현
- 기존 google_compute_url_map에 default_url_redirect 설정을 추가하여 리디렉션 로직을 처리합니다. 이 설정은 쿼리 파라미터를 보존하고 301 (MOVED_PERMANENTLY_DEFAULT) 응답 코드를 사용합니다.
- 수정된 URL 맵을 사용하는 새로운 google_compute_target_http_proxy 리소스를 생성했습니다.
- HTTPS 전달 규칙과 동일한 IP 주소를 사용하고 새로운 HTTP 프록시를 대상으로 하는 포트 80 google_compute_global_forwarding_rule 리소스를 새로 생성했습니다.

Fix: lb redirection

---

argoCD/templates/clustersecretstore.yaml
helm/README.md
helm/springboot-be/Chart.yaml
helm/springboot-be/templates/deployment.yaml
helm/springboot-be/templates/externalsecret.yaml
helm/springboot-be/templates/service.yaml
helm/springboot-be/values.yaml
terraform/gcp/environments/develop/scripts/backend-install.sh.tpl
terraform/gcp/environments/prod/scripts/backend-install.sh.tpl

- (https://github.com/100-hours-a-week/2-hertz-wiki/issues/344)
•	springboot-be용 Helm 차트 디렉토리(helm/springboot-be) 신규 추가
•	Spring Boot Deployment, Service, ExternalSecret 템플릿 작성
•	ExternalSecret을 통한 SSM 파라미터 연동 환경 구성
•	values-dev.yaml 및 values-prod.yaml 환경 분리 설정 추가
•	공통 ClusterSecretStore는 외부에서 관리하도록 분리 (Helm 포함 X)
•	Spring Boot 백엔드를 Helm으로 배포 가능하도록 템플릿을 구성했습니다.
•	ExternalSecret을 이용하여 SSM 파라미터(/global/springboot/dev/)를 자동 주입받아 환경변수를 설정합니다.
•	envFrom.secretRef를 통해 Pod에 환경변수가 삽입되며, readiness 및 liveness probe가 /api/ping으로 설정되어 있습니다.
•	Namespace는 hertz-tuning-dev로 기본 설정되어 있으며, 필요시 values.yaml에서 오버라이드할 수 있습니다.
•	imagePullSecrets, resources, replica 수, readiness/liveness probe 등도 values에서 설정 가능하도록 처리했습니다.

Feat: k8s backend

---

terraform/gcp/modules/external-https-lb/main.tf

- path_prefix_rewrite 변경 `path_prefix_rewrite = "/socket.io"` -> `path_prefix_rewrite = "/socket.io/"`
- 입력: wss://stage.hertz-tuning.com/ws/?EIO=3&transport=websocket
- 매칭: /ws/ 경로가 ["/ws", "/ws/", "/ws/*"]와 매칭
- 재작성: /ws/ → /socket.io/
- 최종 전달: ws://localhost:9100/socket.io/?EIO=3&transport=websocket

fix: path_prefix_rewrite 변경

---

terraform/gcp/environments/prod/main.tf

- feat: 로드밸런서->웹소켓 방화벽 추가 9100
```
{
name          = "${var.vpc_name}-fw-to-websocket"
direction     = "INGRESS"
priority      = 1000
description   = "Allow GCP Health Checks (130.211.0.0/22, 35.191.0.0/16) to websocket on TCP:9100"
source_ranges = [
"130.211.0.0/22",
"35.191.0.0/16",
]
target_tags   = ["websocket","backend"]
protocol      = "tcp"
ports         = ["9100"]
}
```
- 로드밸런서를 통해 웹소켓 서버로 접속이 될 수 있도록 방화벽 추가

feat: 로드밸런서->웹소켓 방화벽 추가

---

terraform/gcp/environments/develop/main.tf
terraform/gcp/environments/develop/variable.tf
terraform/gcp/environments/prod/main.tf
terraform/gcp/environments/prod/variable.tf

- (https://github.com/100-hours-a-week/2-hertz-wiki/issues/396)
- kafka -> be,fe 방화벽 추가
```
{
name        = "${var.env}-fw-kafka-to-kafka"
direction   = "INGRESS"
priority    = 1000
description = "Allow Kafka access from  on ports 9092-9094"
source_ranges = var.kafka_source_ranges
target_tags   = ["backend","frontend"]
ports    = ["9092-9094"]
}
```

fix: kafka 방화벽 추가

---

terraform/gcp/modules/external-https-lb/main.tf

```
path_rule {
paths = [
"/ws",   # wss://…/ws
"/ws/",  # wss://…/ws/
"/ws/*",  # wss://…/ws/anything
"/socket.io",   # wss://…/socket.io
"/socket.io/",  # wss://…/socket.io/
"/socket.io/*"  # wss://…/socket.io/anything
]
```
- k8s alb controller에서 rewrite를 사용하지 않아 /socket.io로 분기 하기로 결정

fix: /socket.io로 보내도 통신이 되도록 수정

---

k8s-argocd-helm/apps/backend/templates/deployment.yaml
k8s-argocd-helm/apps/monitoring/templates/loki.yaml

- FCM 도입으로 fcm.certification json 파일을  마운트 하는 로직 deployment에 추가
```
volumeMounts:
- name: otel-agent
mountPath: /otel
- name: fcm-cert-volume
mountPath: /app
readOnly: true
```
```
volumes:
- name: otel-agent
emptyDir: {}
- name: fcm-cert-volume
secret:
secretName: springboot-secrets
items:
- key: TUNING_FCM
path: tuning-fcm-certification.json
```

feat: FCM secret_key 볼륨 마운트

---

k8s-argocd-helm/apps/backend/templates/deployment.yaml

```
- name: FCM_CERTIFICATION
value: "/app/tuning-fcm-certification.json"
```

fix: fcm.certification 이라는 환경변수를 못 읽어오는 문제 해결

---

k8s-argocd-helm/apps/backend/templates/deployment.yaml

- resources 라닌 디렉토리 자체를 볼륨설정하여 mount
```
- name: fcm-cert-volume
mountPath: /app/resources
readOnly: true
```
```
- name: fcm-cert-volume
secret:
secretName: springboot-fcm-secret
```

fix: fcm resources mount 포인트를 변경

---

k8s-argocd-helm/infrastructure/alb/templates/ingress.yaml

- 로드밸런서 target group의 헬스체크 오류 및 timeout 설정 누락 해결
- 로드밸런서 target group의 헬스체크 오류 및 timeout 설정 누락 해결

fix: 로드밸런서 target group의 헬스체크 오류 및 timeout 설정 누락 해결

---

k8s-argocd-helm/infrastructure/alb/templates/ingress.yaml
k8s-argocd-helm/infrastructure/karpenter/provisioner-general.yaml

- Provisoner에서 스팟 인스턴스를 제외, Provisoner 종류를 1개로 줄임
- Provisoner에서 스팟 인스턴스를 제외, Provisoner 종류를 1개로 줄임

refactor: Provisoner에서 스팟 인스턴스를 제외, Provisoner 종류를 1개로 줄임

---

k8s-argocd-helm/infrastructure/karpenter/provisioner-general.yaml

- 클러스터 기본 워크노드의 감소로 인한 프로비저닝 가능한 CPU 부족 해결
- CPU 제한 조정: `8` -> `16`

refactor: 클러스터 기본 워크노드의 감소로 인한 프로비저닝 가능한 CPU 부족 해결
