- .github/workflows/backend-cd.yml
- 롤백 기능 추가
- dispatch를 이용하여  rollback trigger 추가
- ./be_deploy --rollbaxck 실행
> feature: 롤백 기능 추가

- .github/workflows/Instance_stop.yml
- 인스턴스를 닫습니다.
- 배포 테스트가 끝난 이후 인스턴스를 닫는 스크립트를 실행시킵니다. 
- dispatch 트리거로 수행되며 CD Actions와 다른 스크립트입니다.
> feat: Instance stop

- .github/workflows/backend-cd.yml
> refactor: 30초 대기 설정

- .github/workflows/discord-pr-merged-notify.yml
- X
- PR 메세지가 닫힐 때, 디스코드로 PR 내용을 알려주는 스크립트 추가
- PR 메세지가 닫히고 Merge 됐을 때, PR의 내용을 디스코드로 알려주는 스크립트 추가
- 테스트를 위해 PR 남기는 중
- X
- X
> feat: PR 메세지 알림 기능 추가

- .github/workflows/discord-pr-merged-notify.yml
- #10 
- curl 안의 content를 보내는 형식 재변경
- heredoc 형식에서 기본 형식으로 재수정
- PR에 대한 추가적인 기능으로 PR Merge를 통해 테스트 중입니다.
- x
- x
> fix: 스트립트 내 curl 요청 구문에서 content 형식 재수정

- .github/workflows/discord-pr-merged-notify.yml
- #12 
- 디스코드에 올라올 메세지를 변경함
- 테스트 메세지에서 PR 내용을 포함하는 메세지로 변경
- PR 관련 기능을 테스트하기 위해 PR Merge 중입니다.
- x
- x
> fix: content 안의 테스트 메세지 변경

- .github/workflows/discord-pr-merged-notify.yml
- #16 
- curl의 메세지 본문에 데이터를 담는 방식을 변경
- 스크립트에서 curl 데이터에 변수를 직접 넣어 보내지 않고, 미리 환경변수에 데이터를 넣은 뒤 환경변수로 전달
- 추가로 외부에서 테스트 하기 위해 PR 메세지를 별도로 추출
- PR 관련 기능을 테스트하기 위해 PR Merge 중입니다.
- x
- x
- x
> fix: curl 본문의 내용을 환경변수를 통하여 전달

- .github/workflows/discord-pr-merged-notify.yml
- #18 
- JSON 내부 문자열 처리
- JSON 내부 문자열 처리
- x
- x
> fix: json 내부 문자열 처리

- .github/workflows/discord-pr-merged-notify.yml
- #19 
- curl 요청시 JSON 문법 오류 수정
- curl 요청시 JSON 문법 오류 수정
- x
- x
> fix: curl 요청시 JSON 문법 오류 수정

- .github/workflows/discord-pr-merged-notify.yml
- #20 
- 스크립트 내의 환경변수 설정 위치 변경
- 환경변수 설정 위치를 스크립트 안으로 변경
- x
- x
> fix: 스크립트 내의 환경변수 설정 위치 변경

- .github/workflows/discord-pr-merged-notify.yml
- #21 
- curl 페이로드 전달 방식 변경
- curl 페이로드를 파일로 작성하여 따로 전달
> fix: curl 페이로드 전달 방식 변경

- .github/workflows/backend-cd.yml
> feat: stage project 추가

- .github/workflows/Instance_stop.yml
- .github/workflows/backend-cd.yml
> hotfix: stage 환경 분리

- .github/workflows/Instance_stop.yml
- .github/workflows/backend-cd.yml
> hotfix: stage

- .github/workflows/Instance_stop.yml
> hotfix: selected_SA_KEY

- .github/workflows/Instance_stop.yml
- .github/workflows/backend-cd.yml
> hotfix: service key 주입 실패

- .github/workflows/Instance_stop.yml
> hotfix: 성공할 때만 메시지 전송

- .github/workflows/ai-cd.yml
- X
- 반영되는 브랜치에 따라 알맞은 배포환경(AI서버)에 자동 배포
- main -> production / develop -> stage
- 해당되는 서버를 켠 후, 서버 안의 배포 스크립트 실행
- X
- X
> feat: AI 서버 cd 작성

- .github/workflows/ai-cd.yml
- X
- 환경 변수 변경
- 잘못된 환경 변수 호출 방식 변경
- X
- X
> fix: 환경변수 설정 변경

- .github/workflows/ai-cd.yml
- X
- AI 서버 IP를 담은 별도의 secret 생성 뒤에 반영
- AI 서버 IP를 담은 별도의 secret 생성 뒤에 반영
- X
- X
> fix: AI 서버 HOST 변수 변경

- .github/workflows/ai-cd.yml
- X
- ai서버 자동 배포스크립트에 실패에 대한 디스코드 알림추가
- ai서버 자동 배포스크립트에 실패에 대한 디스코드 알림추가
- X
- X
> feat: ai서버 자동 배포스크립트에 실패에 대한 디스코드 알림추가

- .github/workflows/ai-cd.yml
- X
- (Merge)ai서버 자동 배포스크립트에 실패에 대한 디스코드 알림추가
- ai서버 자동 배포스크립트에 실패에 대한 디스코드 알림추가
- X
- X
> Merge from Develop

- .github/workflows/backend-cd.yml
- X
- 중복되는 환경변수 정의 제거 및 디스코드 알림 메세지 변경
- 중복되는 환경변수 정의 제거 및 디스코드 알림 메세지 변경
[x] PR merge 후 테스트가 가능해 PR 우선 진행
- X
- X
> feat: 환경변수 정의 방법 변경 및 메세지 텍스트 변경

- .github/workflows/backend-cd.yml
- X
- 헬스체크 쪽 URL 변경
- 헬스체크 쪽 URL 변경을 도메인에서 서버IP:PORT로 변경
- X
- X
> fix: 헬스체크 쪽 URL 변경(도메인->서버IP)

- .github/workflows/backend-cd.yml
- X
- production 환경에서의 헬스체크 주소 변경
- 조건문을 넣어 production 환경에서의는 도메인으로 헬스체크 하도록 변경
- X
- X
> fix: production 환경에서의 헬스체크 주소 변경

- .github/workflows/frontend-cd.yml
- fronted cd 코드 
1. npm 캐시 최적화
- actions/cache@v3를 사용하여 ~/.npm 디렉토리를 캐싱
- package-lock.json의 해시값을 기반으로 캐시 키 생성
- 캐시 미스 시에만 npm ci 실행
2. Next.js 빌드 캐시
- .next/cache 디렉토리를 캐싱
- 빌드 결과물을 재사용하여 빌드 시간 단축
3. Node.js 설정 최적화
- actions/setup-node@v3에서 npm 캐시 자동 활성화
- Node.js 버전 18 사용
4. GCP 인증 캐시
- GCP 인증 정보를 ~/.config/gcloud에 캐싱
- 불필요한 재인증 방지
> feat: frontend-cd

- .github/workflows/cd-ai.yml
- .github/workflows/cd-backend.yml
- .github/workflows/deploy-ai.yml
> Merge Develop from Feature/ai cd: AI 서버 헬스체크 URL 변경 및 백엔드 CD 코드 비활성화

- .github/workflows/ci-backend.yml
- .github/workflows/ci-frontend.yml
> feat: add backend CI workflow and update frontend CI notifications

- .github/workflows/deploy-frontend.yml
- X
- Frontend 수동 Deploy 스크립트 추가
- Frontend 수동 Deploy 스크립트 추가
- X
- X
> feat: Frontend 수동 Deploy 스크립트 추가

- landingPage/README.md
- landingPage/index.html
- head에 favicon 경로 지정
- readme 변경
- 랜딩 페이지 접근 오류
> hotfix: 경로 변경, favicon 경로 지정

- backend/workflows/cd-backend.yml
- X
- Secrets Key 가져오는 방식 변경(Github Secrets -> AWS SSM)
- 기존 Github Secrets 방식에서 AWS SSM 방식으로 변경
- PR merge가 되어야 테스트가 되기 때문에 merge 우선 수행
> fix: Secrets Key 가져오는 방식 변경(Github Secrets -> AWS SSM)

- backend/workflows/cd-backend.yml
- x
- actions 트리거 수정
- PR 요청이 merge 됐을 떄 actions 수행되게 트리거 변경
> fix: actions 트리거 수정

- .github/workflows/cd-backend.yml
- x
- PR이 merge 됐을 때 동작하도록 트리거 변경
- PR이 merge 됐을 때 동작하도록 트리거 변경
> fix: PR이 merge 됐을 때 동작하도록 트리거 변경

- .github/workflows/cd-backend.yml
- .github/workflows/rollback-backend.yml
백엔드 cd 테스트를 위해 rollback 스크립트 이동
> test: 백엔드 cd 테스트를 위해 rollback 스크립트 이동

- .github/workflows/cd-backend.yml
- x
- 시크릿키에서 json 파일 가져오는 오류해결 및 수동 트리거 추가
> 시크릿키에서 json 파일 가져오는 오류해결 및 수동 트리거 추가

- .github/workflows/cd-backend.yml
- .gitignore
- terraform/environments/global/ssm_parameters/ssm-gcp/.terraform.lock.hcl
- terraform/environments/global/ssm_parameters/ssm-gcp/main.tf
- terraform/environments/global/ssm_parameters/ssm-gcp/variables.tf
- terraform/environments/global/ssm_parameters/ssm-nextjs/.terraform.lock.hcl
- terraform/environments/global/ssm_parameters/ssm-nextjs/main.tf
- terraform/environments/global/ssm_parameters/ssm-nextjs/variables.tf
- terraform/environments/global/ssm_parameters/ssm-springboot/.terraform.lock.hcl
- terraform/environments/global/ssm_parameters/ssm-springboot/main.tf
- terraform/environments/global/ssm_parameters/ssm-springboot/variables.tf
- terraform/modules/ecr/main.tf
- terraform/modules/ssm_parameter/main.tf
- terraform/modules/ssm_parameter/outputs.tf
- terraform/modules/ssm_parameter/variables.tf
- x
- AWS Access 키
- GCP 크리덴셜키
> fix: 백엔드 CD - 가져온 시크릿키 알맞게 변환

- backend/workflows/cd-backend.yml
> fix: 환경변수 마스킹 처리

- backend/workflows/cd-backend.yml
- x
- key 모두 마스킹 처리 및 GCP_SA_KEY 안읽히는 문제 해결
- 공개가 되면 안되는 중요 key -> 모두 마스킹 처리
- GCP_SA_KEY가 JSON 파싱 문제로 안읽히는 문제 해결
- x
- x
> fix: 중요 key 모두 마스킹 처리 및 GCP_SA_KEY 안읽히는 문제 해결

- ai/docker/Dockerfile
- ai/docker/docker-compose-local.yml
- ai/workflows/docker-ci-ai.yml
- requirement-dev.txt 삭제 (ci, docker-compose, dockerfile)
- 로컬환경에서만 필요함
> refactor: 불필요한 파일 삭제

- .github/workflows/cd-frontend.yml
> test: 롤백 트리거 테스트

- .github/workflows/cd-frontend.yml
> test: rollback 트리거 변경 후 테스트

- .github/workflows/cd-frontend.yml
- rollback을 실행하는 부분 수정 후 테스트(OUTPUT로 배포실패 여부 및 브랜치 확인)
- rollback을 실행하는 부분 수정 후 테스트(OUTPUT로 배포실패 여부 및 브랜치 확인)
> test: rollback을 실행하는 부분 수정 후 테스트(OUTPUT로 배포실패 여부 및 브랜치 확인)

- .github/workflows/cd-frontend.yml
- x
- 
- CD 및 Rollback 스크립트 통합
- CD 및 Rollback 스크립트 통합
> feat: CD 및 Rollback 스크립트 통합

- .github/workflows/cd-frontend.yml
> test: frontend 롤백 테스트

- frontend/workflows/cicd-frontend.yml
- terraform/environments/global/ssm_parameters/ssm-nextjs/main.tf
- terraform/environments/global/ssm_parameters/ssm-springboot/main.tf
- x
- ci 파일과 cd 파일 통합
- ci 파일과 cd 파일 통합(ci 잡에 대한 cd의 의존성 처리)
- ci 부분 테스트 전이므로 주석처리
> chore: ci 파일과 cd 파일 통합

- frontend/workflows/cicd-frontend.yml
- x
- 디스코드 알림 출력메세지 변경(production -> PROD / develop -> DEV)
- 환경변수 ENV의 값 변경: production -> PROD / develop -> DEV
> style: 디스코드 알림 출력메세지 변경(production -> PROD / develop -> DEV)

- terraform/environments/global/ssm_parameters/ssm-gcp/main.tf
- terraform/environments/global/ssm_parameters/ssm-nextjs/main.tf
- terraform/environments/global/ssm_parameters/ssm-springboot/main.tf
- Terraform Cloud 연동을 위한 코드 삽입
- Terraform Cloud 연동을 위한 코드 삽입
> chore: Terraform Cloud 연동을 위한 코드 삽입

- terraform/environments/global/ssm_parameters/ssm-gcp/main.tf
- terraform/environments/global/ssm_parameters/ssm-gcp/variables.tf
- terraform/environments/global/ssm_parameters/ssm-nextjs/main.tf
- terraform/environments/global/ssm_parameters/ssm-nextjs/variables.tf
- terraform/environments/global/ssm_parameters/ssm-springboot/main.tf
- terraform/environments/global/ssm_parameters/ssm-springboot/variables.tf
- terraform/environments/shared/main.tf
- terraform/environments/shared/variables.tf
- AWS region 변수화
- AWS region 변수화
> chore: AWS region 변수화

- terraform/environments/shared/main.tf
- terraform/modules/ec2-openvpn/main.tf
- terraform/modules/ec2-openvpn/scripts/openvpn-install.sh
- terraform/modules/ec2-openvpn/scripts/user_data.sh.tpl
- openvpn user_data를 추가
- bastion 서버에 openvpn 자동 설치
> feat: openvpn user_data 추가

- terraform/modules/ec2-openvpn/scripts/user_data.sh.tpl
> fix: ec2-user에서 openvpnas로 변경

- terraform/environments/shared/main.tf
> fix: user_data 주석

- .github/workflows/cd-frontend.yml
> fix: frontend cicd 스크립트 중 배포환경 구분이 안되는 오류 해결

- .github/workflows/cd-frontend.yml
> fix: CICD 배포환경 오류 해결

- frontend/workflows/cicd-frontend.yml
> chore: frontend CICD 동작 안하게 위치 변경

- terraform/environments/shared/main.tf
- terraform/environments/shared/scripts/openvpn-init.sh.tpl
- terraform/environments/shared/variables.tf
- user_data추가로 openvpn 기본 응답 및 비밀번호 설정
> feat: user_data 추가

- terraform/environments/shared/scripts/openvpn-init.sh.tpl
> fix: 다시 수정

- terraform/environments/shared/scripts/openvpn-init.sh.tpl
[Sprint #4 - CL] - terraform-openvpn
[#215](https://github.com/100-hours-a-week/2-hertz-wiki/issues/215)
- 루트 비밀번호 변경 부분 수정
> fix: 비밀번호 입력 부분 수정

- terraform/environments/shared/scripts/openvpn-init.sh.tpl
- terraform/environments/shared/scripts/openvpn-install.sh
[Sprint #4 - CL] - terraform-openvpn
[#215](https://github.com/100-hours-a-week/2-hertz-wiki/issues/215)
- 초기 비밀번호 부분이 작동하지 않음
> fix: 비밀번호 변경 부분 수정

- terraform/environments/shared/scripts/openvpn-init.sh.tpl
[Sprint #4 - CL] - terraform-openvpn
[#215](https://github.com/100-hours-a-week/2-hertz-wiki/issues/215)
- 재시작 이후 비밀번호 변경하는 것으로 수정
- 비밀번호 변경이 작동하지 않음
> fix: 서비스 재시작 로직 추가

- terraform/environments/shared/main.tf
[Sprint #4 - CL] - terraform-ec2
[#221](https://github.com/100-hours-a-week/2-hertz-wiki/issues/221)
- ami 변경
> fix: ami 수정

- terraform/environments/shared/main.tf
- terraform/environments/shared/scripts/ec2-init.sh.tpl
- 서브넷을 private에서 nat 서브넷으로 변경
- private 서브넷은 DB와 연결하는 서브넷입니다.
> fix: 서브넷을 nat 서브넷으로 변경

- terraform/environments/shared/scripts/openvpn-init.sh.tpl
> fix: openvpn 자동응답 수정

- terraform/environments/shared/scripts/openvpn-init.sh.tpl
> fix: 스크립트 수정

- terraform/environments/shared/scripts/ec2-init.sh.tpl
- ec2에 deploy 계정으로 접속 가능하도록 ssh 키 복사
> feat: ssh 키 복사하여 deploy 계정에 등록

- .github/workflows/cicd-frontend.yml
- frontend cicd 중 rollback으로 안넘어가는 오류 수정 후 테스트
- 실패 알림 step에 롤백의 트리거가 되는 변수값 할당하는 코드 추가
> test: frontend cicd 중 rollback으로 안넘어가는 오류 수정 후 테스트

- .github/workflows/deploy-ai.yml
> hotfix: AI_ZONE 변경

- .github/workflows/deploy-ai.yml
> hotfix: zone 변경

- .github/workflows/deploy-ai.yml
- ai/docker/docker-compose-tuning.yml
- ai/workflows/deploy_docker-tuning.yml
- ai/workflows/deploy_workflow-tuning.yml
- deploy 코드에 docker 배포 선택지도 추가
> feat: 도커 CI/CD 반영

- .github/workflows/deploy-ai.yml
> hotfix: 구문 오류 수정

- terraform/gcp/modules/network/main.tf
[Sprint #5 - CL] - terraform 네트워크 구축
[#245](https://github.com/100-hours-a-week/2-hertz-wiki/issues/245)
- nat 서브넷 라우팅, 고정 IP 추가
> feat: nat, 고정 IP 추가

- terraform/gcp/environments/shared/main.tf
- terraform/gcp/environments/shared/scripts/install-openvpn.sh.tpl
- terraform/gcp/environments/shared/variables.tf
- terraform/gcp/modules/compute/main.tf
- terraform/gcp/modules/compute/variables.tf
[Sprint #5 - CL] - gcp-openvpn
[#249](https://github.com/100-hours-a-week/2-hertz-wiki/issues/249)
- openvpn 용 서버를 추가
- openvpn 용 vm 추가, compute 모듈 추가, init .tpl 추가
> feat: openvpn 추가

- terraform/gcp/environments/develop/main.tf
> feat: data.shared로 값 가져오기

- terraform/gcp/environments/develop/main.tf
[Sprint #5 - CL] -mig-asg
[#268](https://github.com/100-hours-a-week/2-hertz-wiki/issues/268)
-  `subnet_self_link  = data.terraform_remote_state.shared.outputs.nat_b_subnet_self_link`
> fix: asg 네트워크 Error: exactly one of network 오류 해결

- .github/workflows/stop-gcp-instance.yml
- x
- AI 서의 변경된 ZONE이 반영되어 있지 않아 중지가 되지않는 오류 수정
- AI 서의 변경된 ZONE을 시크릿키에 새로 등록하고, 스크립트 조건문에 해당 시크릿키를 가져오게 반영
> hotfix: AI 서의 변경된 ZONE이 반영되어 있지 않아 중지가 되지않는 오류 수정

- terraform/gcp/environments/develop/main.tf
- terraform/gcp/modules/internal-http-lb/main.tf
- terraform/gcp/modules/internal-http-lb/output.tf
> bugfix: backend mig capcity_scaler 통일

- terraform/gcp/environments/develop/main.tf
- terraform/gcp/environments/develop/output.tf
- terraform/gcp/environments/develop/variable.tf
- weight 등의 값을 동적으로 변경 가능하게 수정
> feat: 동적 blue/green 배포

- .github/workflows/stop-gcp-instance.yml
[Sprint #5 - CL] - GPU 서버 구축
[#273](https://github.com/100-hours-a-week/2-hertz-wiki/issues/273)
- GPU 서버 중지 기능 추가
PROD_INSTANCE_GPU: ${{ secrets.PROD_INSTANCE_GPU }}
PROJECT_ID_GPU: ${{ secrets.PROJECT_ID_GPU }}
credentials_json: ${{ secrets.PROD_GPU_SA_KEY }}
> feat: GPU 서버 중지

- terraform/gcp/environments/shared/main.tf
- terraform/gcp/environments/shared/output.tf
> fix: 헬스체크 shared로 이동, nat-a 서브넷 추가

- terraform/gcp/environments/prod/main.tf
- terraform/gcp/modules/external-https-lb/main.tf
> hotfix: prod에 extenal_ip 연결

- terraform/gcp/environments/develop/main.tf
- terraform/gcp/environments/develop/scripts/vm-install.sh.tpl
- terraform/gcp/environments/prod/scripts/vm-install.sh.tpl
> fix: vm-instal.sh 수정

- terraform/gcp/environments/develop/scripts/vm-install.sh.tpl
- terraform/gcp/environments/prod/scripts/vm-install.sh.tpl
> fix: vm-install.sh 수정

- terraform/gcp/environments/develop/scripts/vm-install.sh.tpl
- terraform/gcp/environments/prod/scripts/vm-install.sh.tpl
> fix: vm-install

- terraform/gcp/environments/develop/main.tf
- terraform/gcp/environments/develop/scripts/backend-install.sh.tpl
- terraform/gcp/environments/develop/scripts/db-install.sh.tpl
- terraform/gcp/environments/develop/variable.tf
-  DB에 내부 IP 고정 
- DB 인스턴스 private subnet에서 세팅
> feat: DB에 내부 IP 고정 

- terraform/gcp/environments/prod/main.tf
- terraform/gcp/modules/external-https-lb/main.tf
- terraform/gcp/modules/external-https-lb/variables.tf
- terraform/gcp/modules/internal-http-lb/main.tf
- terraform/gcp/modules/internal-http-lb/variables.tf
- terraform/gcp/modules/mig-asg/main.tf
> fix: 중복 리소스 수정

- terraform/gcp/environments/prod/main.tf
- terraform/gcp/environments/prod/scripts/db-install.sh.tpl
- terraform/gcp/environments/prod/variable.tf
> hotfix: 반영 안된 것들 수정

- terraform/gcp/environments/develop/main.tf
- terraform/gcp/environments/prod/main.tf
- terraform/gcp/modules/mig-asg/main.tf
> hotfix: life cycle 설정 , db zone 수정

- terraform/gcp/environments/prod/main.tf
- asg 템플릿에 도커 이미지 변수명이 잘못되어 수정함
- `docker_image = var.docker_image_backend_blue` -> `docker_image = var.docker_image_backend_green`
> fix: 오타 수정(blue -> green)

- terraform/gcp/environments/prod/main.tf
- ASG desired 설정 주석처리
- ASG 설정에서 desired 변수를 더 이상 사용하지 않아 주석처리
> fix: ASG desired 설정 주석처리(front 부분)

- terraform/gcp/environments/prod/variable.tf
- ASG 설정에서 desired 변수를 더이상 삭제하지 않아 주석처리(variable.tf 파일)
- ASG 설정에서 desired 변수를 더이상 삭제하지 않아 주석처리(variable.tf 파일)
- green 쪽 max를 0으로 변경(아예 생성되지 않게하기 위해서)
> fix: ASG 설정에서 desired 변수를 더이상 삭제하지 않아 주석처리(variable.tf 파일)

- terraform/gcp/environments/prod/variable.tf
- variable에 없는 변수 선언
- deploy_ssh_public_key 변수 선언
> fix: variable에 없는 변수 선언

- terraform/gcp/environments/prod/output.tf
- 디버깅을 위한 output 수정
- 트래픽이 올바르게 옮겨졌는지 알기 위해 다음 값을 output에 추가
```
output "green_instance_count" {
value = var.green_instance_count
}
output "traffic_weight_green" {
value = var.traffic_weight_green
}
```
> refator: 디버깅을 위한 output 수정

- terraform/gcp/environments/prod/main.tf
- interbal_lb의 capacity_scaler도 동적으로 변경되게 반영
- interbal_lb의 capacity_scaler도 external_lb처럼 동적으로 변경되게 반영
> fix: interbal_lb의 capacity_scaler도 동적으로 변경되게 반영

- terraform/gcp/environments/prod/scripts/backend-install.sh.tpl
- terraform/gcp/modules/mig-asg/main.tf
- aws-cli및 docker가 설치된 vm 이미지 적용
- aws-cli및 docker가 설치된 vm 이미지를 별도로 만들어 적용
> feat: aws-cli및 docker가 설치된 vm 이미지 적용

- terraform/gcp/environments/develop/main.tf
- terraform/gcp/environments/prod/main.tf
- ssm 파라미터 path 변경 (환경별)
- nat 관련 리소스 이름 변경 
-  리소스 중복 문제를 해결하기 위해 다음과 같이 변경 ${var.vpc_name}-nat -> ${var.env}-nat
- 환경변수를 환경에 맞게 지정하기 위해 다음과 같이 구성  /global/springboot/ -> /global/springboot/prod/
> refactor: 환경변수 수정, nat 리소스 이름 변경 ( var.vpc_name -> var.env)

- terraform/gcp/environments/prod/variable.tf
- terraform/gcp/modules/mig-asg/main.tf
- ASG 기본 트래픽량 수정 및 base 이미지 변경(aws-cli 및 docker 설치된 이미지)
- ASG 기본 트래픽량 수정: blue 0 / green 0 -> blue 0 / green 10
- base 이미지 변경(aws-cli 및 docker 설치된 이미지)
> fix&refactor: ASG 기본 트래픽량 수정 및 base 이미지 변경(aws-cli 및 docker 설치된 이미지)

- terraform/gcp/environments/develop/main.tf
- terraform/gcp/environments/develop/scripts/backend-install.sh.tpl
- terraform/gcp/environments/develop/scripts/db-install.sh.tpl
- terraform/gcp/environments/develop/scripts/frontend-install.sh.tpl
- terraform/gcp/environments/prod/scripts/db-install.sh.tpl
- terraform/gcp/environments/shared-dev/main.tf
- db 마운트 부분 bugfix
- base-vm-template dev에도 반영
> fix: db 마운트 부분 수정, base 이미지 적용

- terraform/gcp/environments/prod/main.tf
- terraform/gcp/environments/prod/output.tf
- terraform/gcp/environments/prod/variable.tf
- 블루-그린 배포에 사용되는 변수를 Frontend와 Backend로 분리
- 기존) 하나의 변수를 통해 블루-그린 MIG 전환
- 수정) MIG 전환의 기준이 되는 변수를 _frontend와 _backend 접미사로 분리
- main.tf, variable.tf, output.tf 모두 수정
> refactor: 블루-그린 배포에 사용되는 변수를 Frontend와 Backend로 분리

- frontend/workflows/docker-cicd-frontend.yml
- env.DEV로 나눙어 develop 서버로 배포 되도록 수정
- 롤백은 prod에서만 진행
```hcp
- name: Deploy to Dev Environment
if: env.ENV == 'DEV'
working-directory: tf-code/terraform/gcp/environments/develop
```
```
- name: Get Active Deployment Color
if: env.ENV == 'PROD'
id: active
working-directory: tf-code/terraform/gcp/environments/prod
```
> feat: fe_ci/cd develop 환경 추가

- frontend/workflows/docker-cicd-frontend.yml
- terraform/gcp/environments/develop/main.tf
-  ig->mig로 변경 , bugfix
- 기존은 dev 환경에서 unmanaged 인스턴스 그룹을 사용하고 있어서 이를 mig로 변경
- 오타 수정
> fix: ig->mig로 변경 , bugfix

- terraform/gcp/environments/develop/main.tf
> fix: bugfix

- frontend/workflows/docker-cicd-frontend.yml
- terraform/gcp/environments/develop/main.tf
- terraform/gcp/environments/develop/variable.tf
> hotfix: 이미지 변수 수정

- terraform/gcp/environments/develop/variable.tf
> hotfix: 변수 이름 중복

- .github/workflows/deploy-gpu.yml
- frontend/workflows/docker-cicd-frontend-act.yml
- terraform/gcp/environments/develop/main.tf
- terraform/gcp/modules/mig-asg/main.tf
- terraform/gcp/modules/mig-asg/variables.tf
> feat: gpu-deploy

- .github/workflows/deploy-gpu.yml
> hotfix: 롤백 헬스체크 수정

- frontend/workflows/docker-cicd-frontend.yml
- DEV 환경 중복알림 제거
- DEV 환경 중복알림 제거
> refactor: DEV 환경 중복알림 제거

- backend/workflows/docker-cicd-backend.yml
- frontend/workflows/docker-cicd-frontend.yml
- DEV 환경 Docker CI/CD 추가(백엔드)
- DEV 환경 Docker CI/CD 추가(백엔드)
> feat: DEV 환경 Docker CI/CD 추가(백엔드)

- backend/workflows/docker-cicd-backend.yml
-  ig 이름 ->  dev-be-ig-a
- 이미지 이름 -> docker_image_back_blue
- 프론트 코드에서 다른 점 수정
> fix: 백엔드 CI/CD 오타 수정

- terraform/gcp/environments/develop/main.tf
- terraform/gcp/environments/develop/scripts/backend-install.sh.tpl
- terraform/gcp/environments/develop/scripts/db-install.sh.tpl
- terraform/gcp/environments/develop/scripts/frontend-install.sh.tpl
- terraform/gcp/environments/develop/variable.tf
- terraform/gcp/environments/prod/main.tf
- terraform/gcp/environments/prod/scripts/backend-install.sh.tpl
- terraform/gcp/environments/prod/scripts/db-install.sh.tpl
- terraform/gcp/environments/prod/scripts/frontend-install.sh.tpl
- terraform/gcp/environments/prod/variable.tf
- terraform/gcp/modules/mig-asg/main.tf
- terraform/gcp/modules/mig-asg/variables.tf
- db 컨테이너에 redis 추가
- ssh 키 등록 로직 수정
> feat: redis 추가

- terraform/gcp/environments/develop/main.tf
- terraform/gcp/environments/develop/scripts/db-install.sh.tpl
- terraform/gcp/environments/prod/main.tf
- terraform/gcp/environments/prod/scripts/db-install.sh.tpl
-  `-v $${MOUNT_POINT}/redis_data:/data \ ` redis 볼륨 추가
-  방화벽 var.env 로 시작하도록 변경
> fix: redis 볼륨 설정, 방화벽 수정

- backend/workflows/docker-cicd-backend.yml
- frontend/workflows/docker-cicd-frontend.yml
> fix: 테라폼 설치

- .github/workflows/deploy-backend.yml
- .github/workflows/deploy-frontend.yml
- 헬스체크 시간 및 횟수 증가
- 배포 시간이 길어질 경우 헬스체크가 되지 않는 오류가 있어, 헬스체크 기간 증가
- 헬스체크 시간 및 횟수 증가
> refactor: 헬스체크 시간 및 횟수 증가

- terraform/gcp/modules/mig-asg/main.tf
> fix: rollback

- terraform/gcp/modules/mig-asg/main.tf
-
```
update_policy {
type                         = "PROACTIVE"
minimal_action               = "REPLACE"
max_surge_fixed              = 3
max_unavailable_fixed        = 0
most_disruptive_allowed_action = "REPLACE"
}
```
•	type = PROACTIVE: 템플릿 변경이 감지되면 즉시 교체를 시작
•	minimal_action = REPLACE: 기존 인스턴스를 삭제 후 새 인스턴스로 교체
•	max_surge_fixed = 3: 한 번에 존(zone) 수만큼(=3대)까지 미리 생성 → 빠른 교체 지원
•	max_unavailable_fixed = 0: 교체 중 절대 중단 없음 → 무중단(Zero-downtime) 보장
•	most_disruptive_allowed_action = REPLACE: 완전 교체까지 허용하여 확실한 업데이트 실행
> feat: update_policy 설정

- .github/workflows/deploy-gpu.yml
- vllm 헬스체크 추가
- vllm 서버가 켜지는데 시간이 오래 걸려 해당 부분을 헬스체크를 추가하고 시간을 늘림
> fix: vllm 헬스체크 추가

- frontend/workflows/docker-cicd-frontend.yml
- terraform/gcp/environments/prod/scripts/backend-install.sh.tpl
- terraform/gcp/environments/prod/scripts/frontend-install.sh.tpl
- websocket/docker/README.md
> fix: 프론트엔드  CI/CD

- terraform/gcp/modules/mig-asg/main.tf
- MIG template disk 속성 변경
기존)
type         = "pd-balanced"
변경)
type         = "PERSISTENT"
disk_type    = "pd-balanced"
> fix: MIG template disk 속성 변경

- backend/workflows/docker-cicd-backend.yml
- terraform/gcp/environments/develop/main.tf
- terraform/gcp/environments/develop/scripts/backend-install.sh.tpl
- terraform/gcp/environments/prod/main.tf
- terraform/gcp/environments/prod/scripts/backend-install.sh.tpl
- terraform/gcp/modules/external-https-lb/main.tf
- terraform/gcp/modules/external-https-lb/variables.tf
- [Sprint #6 - CL] - 웹 소켓 구축
[#325](https://github.com/100-hours-a-week/2-hertz-wiki/issues/325)
- 웹소켓 리소스 주석 처리
- 백엔드 포트 추가
- 웹소켓을 spring과 통합으로 인한 변경
> feat: 웹소켓 통합

- .github/workflows/deploy-gpu.yml
- backend/workflows/docker-cicd-backend.yml
- frontend/workflows/docker-cicd-frontend.yml
- terraform/gcp/environments/prod/main.tf
- gpu-deploy 가상 환경 활성화 추가
-  docker-cicd 수정
- internal_lb 주석처리
- gpu-deploy에서 가상환경이 활성화 되지 않아 배포에 문제가 발생하는 경우가 지속적으로 발생
- scaler가 가변적으로 변하는 상황에서 internal_lb와 같은 backend_service를 사용하고 있어 문제 발생
> fix: docker-cicd 수정 , gpu-deploy 가상 환경 활성화 추가

- backend/workflows/docker-cicd-backend.yml
- frontend/workflows/docker-cicd-frontend.yml
- dispatch 수동 배포도 가능하도록 수정
```
options:
- main
- develop
```
> feat: 최종 도커 CI/CD

- backend/workflows/docker-cicd-backend.yml
- 환경변수 Redirec URL 값을 바꾸는 로직 추가
- FE 개발을 위한 DEV 서버의 Redirect URL 값 변경 로직 추가
- local 환경과 Dev 백엔드 환경을 구분하여 값 변경
- Secrets 추가 필요
`SSM_PATH_REDIRECT_URL`: SSM에 있는 REDIRECT_URL 이름(path)
`REDIRECT_URL_LOCAL`: FE local 개발을 위한 REDIRECT_URL
`REDIRECT_URL_DEV`: BE 환경과 연동을 위한 REDIRECT_URL
> feat: 환경변수 Redirec URL 값을 바꾸는 로직 추가

- .github/workflows/deploy-gpu.yml
- GPU 서버 헬스체크 인터벌 수정(60->30초)
- GPU 서버 헬스체크 인터벌 수정(60->30초)
> refactor: GPU 서버 헬스체크 인터벌 수정(60->30초)

- helm/README.md
- helm/nextjs-fe/.helmignore
- helm/nextjs-fe/Chart.yaml
- helm/nextjs-fe/templates/deployment.yaml
- helm/nextjs-fe/templates/ingress.yaml
- helm/nextjs-fe/templates/service.yaml
- helm/nextjs-fe/values-dev.yaml
- helm/nextjs-fe/values-prod.yaml
- helm/nextjs-fe/values.yaml
- terraform/environments/shared/main.tf
- terraform/modules/subnet/main.tf
- (https://github.com/100-hours-a-week/2-hertz-wiki/issues/342)(https://github.com/100-hours-a-week/2-hertz-wiki/issues/342)
- nextjs-ingress
- nextjs-service
- nextjs-deployment
- helm chart 구조 생성
> feat: helm-chart , nginx ingress

- terraform/gcp/modules/external-https-lb/main.tf
- 리디렉션용 url map 생성하여 분리
```
resource "google_compute_url_map" "http_redirect_url_map" {
name = "${var.name}-http-redirect-url-map-${var.env}"
default_url_redirect {
https_redirect         = true
strip_query            = false
redirect_response_code = "MOVED_PERMANENTLY_DEFAULT"
}
}
```
> hotfix: default 속성 분리

- terraform/gcp/environments/prod/main.tf
- terraform/gcp/environments/shared/main.tf
- 사용하지 않는 방화벽 삭제(websocket, 중복)
- 초기, 웹소케 서버 분리 시 필요했던 방화벽 설정 제거(주석처리)
- 프론트엔드 쪽에 중복되는 방화벽 제거(주석처리)
> refactor: 사용하지 않는 방화벽 삭제(websocket, 중복)

- terraform/gcp/modules/external-https-lb/main.tf
> hotfix: 리소스 명 수정

- terraform/gcp/environments/develop/scripts/backend-install.sh.tpl
- terraform/gcp/environments/develop/scripts/frontend-install.sh.tpl
- terraform/gcp/environments/prod/scripts/backend-install.sh.tpl
- terraform/gcp/environments/prod/scripts/frontend-install.sh.tpl
- timedatectl set-timezone Asia/Seoul
- timedatectl set-ntp true
- timezone 수정하여 시간 맞추기
> hotfix: timezone 수정

- terraform/gcp/environments/develop/scripts/backend-install.sh.tpl
- STAGE 쪽 로그 모니터링의 host 이름 변경
- 환경 구분을 위한 prefix `stage-` 추가
> style: STAGE 쪽 로그 모니터링의 host 이름 변경

- terraform/gcp/environments/prod/main.tf
> refactor: prod에도 적용

- terraform/gcp/environments/develop/scripts/backend-install.sh.tpl
- terraform/gcp/environments/prod/scripts/backend-install.sh.tpl
> fix: 로그 중복 제거

- terraform/gcp/environments/develop/scripts/backend-install.sh.tpl
- terraform/gcp/environments/prod/scripts/backend-install.sh.tpl
- signoz 내부 네트워크 추가
- 도커 signoz 내부 네트워크 추가
> fix: signoz 내부 네트워크 추가

- .github/workflows/deploy-backend.yml
- .github/workflows/deploy-frontend.yml
- 디스코드 알림 메세지 변경(STAGE -> DEV)
- 디스코드 알림 메세지 변경(STAGE -> DEV)
> fix: 디스코드 알림 메세지 변경(STAGE -> DEV)

- terraform/gcp/environments/develop/main.tf
- terraform/gcp/environments/prod/main.tf
- ws protocal_name을 "HTTP"로 명시
-  웹 소켓이 HTTP/1.1에서만 지원
> fix: 웹소켓 프로토콜 HTTP 명시

- terraform/gcp/modules/external-https-lb/main.tf
-   
```
path_rule {
paths = [
"/ws",   # wss://…/ws
"/ws/",  # wss://…/ws/
"/ws/*"  # wss://…/ws/anything
]
```
- /ws/* 에서 path룰 추가
> fix: 웹 소켓 path 룰 추가

- terraform/gcp/environments/develop/main.tf
- terraform/gcp/environments/develop/scripts/kafka-install.sh.tpl
- terraform/gcp/environments/develop/variable.tf
- terraform/gcp/environments/prod/main.tf
- (https://github.com/100-hours-a-week/2-hertz-wiki/issues/396)
- kafaka 서버 일시적으로 nat 서브넷에 올리기
- nat에 올려놓고 이미지화 하여 배포 예정
> feat: kafka 서버 구축

- terraform/gcp/environments/develop/main.tf
> fix: 임시 nat 서브넷으로 변경

- terraform/gcp/environments/develop/scripts/backend-install.sh.tpl
- terraform/gcp/environments/prod/scripts/backend-install.sh.tpl
- terraform/gcp/modules/mig-asg/variables.tf
- network 모드 변경
- 9100번대로 ws 포트 변경
> fix: network 모드 변경, 9100번대로 ws 포트 변경

- terraform/modules/subnet/main.tf
- NAT 서브넷 추가
- ap-northeast-2c에 NAT 서브넷 추가
> feat: NAT 서브넷 추가

- terraform/gcp/modules/external-https-lb/main.tf
> hotfix: rollback

- terraform/gcp/modules/external-https-lb/main.tf
> fix: socket.io path 추가

- k8s/app/springboot-backend-deployment.yaml
- k8s/signoz/install-signoz.sh
- k8s/signoz/namespace.yaml
- k8s/signoz/signoz-values.yaml
> feat: signoz springbackend

- k8s-argocd-helm/apps/signoz/Chart.yaml
- k8s-argocd-helm/apps/signoz/values.yaml
- k8s-infra 추가 
- 무거운 리소스들 false로 변경
- infra metric을 가져올 수 있도록 수정
- kafka, zookeeper, alertmanger를 enable -> false
> fix: k8s-infra 추가 , 무거운 리소스들 false로 변경

- k8s-argocd-helm/apps/signoz/Chart.yaml
- k8s-infra 의존성 버전 변경
- k8s-infra 의존성 버전 변경
> fix: k8s-infra 의존성 버전 변경

- k8s-argocd-helm/apps/signoz/Chart.yaml
- k8s-argocd-helm/apps/signoz/values.yaml
- signoz k8s-infra 의존성 해결
- signoz k8s-infra 의존성 해결
> fix: signoz k8s-infra 의존성 해결

- k8s-argocd-helm/Chart.yaml
- k8s-argocd-helm/apps/backend/templates/deployment.yaml
- k8s-argocd-helm/apps/frontend/templates/deployment.yaml
- k8s-argocd-helm/argocd/templates/applications/infrastructure/reloader-application.yaml
- k8s-argocd-helm/infrastructure/reloader/Chart.yaml
- k8s-argocd-helm/infrastructure/reloader/values.yaml
- k8s-argocd-helm/infrastructure/secrets/templates/externalsecret.yaml
- k8s-argocd-helm/values.yaml
- reloader 추가
- ssm 변경점을 트리거하여 재배포
- 1m 간격으로 ssm이 변경되었는지 검사 
- reloader chart 추가
> feat: reloader

- k8s-argocd-helm/infrastructure/reloader/values.yaml
-     ```# 네임스페이스 권한 불필요하도록 설정
isArgoRollouts: false
isOpenshift: false
rbac:
create: true
clusterRole: false
serviceAccount:
create: true
```
> hotfix: reloader 권한 문제 해결

- k8s-argocd-helm/argocd/Chart.yaml
- k8s-argocd-helm/argocd/templates/applications/apps/backend-application.yaml
- k8s-argocd-helm/argocd/templates/applications/apps/frontend-application.yaml
- k8s-argocd-helm/argocd/values.yaml
> hotfix: image-updater

- k8s-argocd-helm/argocd/templates/projects/tuning-project-dev.yaml
- ArgoCD 생성 시 project가 가장 먼저 생성되게 우선순위 조정
- ArgoCD 자원생성 우선순위: -1
- helm.sh/hook: post-install,post-upgrade -> pre-install,pre-upgrade
> fix: ArgoCD 생성 시 project가 가장 먼저 생성되게 우선순위 조정

- k8s-argocd-helm/argocd/templates/projects/tuning-project-dev.yaml
- ArgoCD 최초 실행 시 project가 설치되지 않는 오류 수정
- ArgoCD 최초 실행 시 project가 설치되지 않는 오류 수정
> fix: ArgoCD 최초 실행 시 project가 설치되지 않는 오류 수정

- k8s-argocd-helm/argocd/templates/applications/apps/backend-application.yaml
- k8s-argocd-helm/argocd/templates/applications/apps/frontend-application.yaml
- k8s-argocd-helm/argocd/templates/applications/apps/kafka-application.yaml
- k8s-argocd-helm/argocd/templates/applications/apps/mysql-application.yaml
- k8s-argocd-helm/argocd/templates/applications/apps/redis-application.yaml
- k8s-argocd-helm/argocd/templates/applications/apps/signoz-application.yaml
- k8s-argocd-helm/argocd/templates/applications/infrastructure/alb-application.yaml
- k8s-argocd-helm/argocd/templates/applications/infrastructure/network-application.yaml
- k8s-argocd-helm/argocd/templates/applications/infrastructure/reloader-application.yaml
- k8s-argocd-helm/argocd/templates/applications/infrastructure/secrets-application.yaml
- k8s-argocd-helm/argocd/values.yaml
- argocd template의 targetRevion을 가변적으로 변할 수 있도록 수정
```
applications:
git:
targetRevision: develop  # 기본 브랜치
branches:
dev: develop
staging: staging
prod: main
```
`targetRevision: {{ .Values.applications.git.targetRevision }}`
> refactor: targetRevision helm-chart화

- k8s-argocd-helm/apps/backend/values.yaml
> fix: 백엔드 리소스량 제한

- k8s-argocd-helm/infrastructure/alb/templates/ingress.yaml
> fix: v3 추가

- terraform/gcp/modules/external-https-lb/main.tf
> hotfix: http-fr 임시 삭제

- .github/workflows/k8s-deploy-by-commit.yml
- k8s-argocd-helm/argocd/templates/projects/tuning-project-dev.yaml
- image updater가 잘 작동하지 않는 문제가 있어 manifest를 커밋 푸시 하도록 수정
```
- name: Clone cloud repository
uses: actions/checkout@v3
with:
repository: 100-hourbackends-a-week/2-hertz-cloud
token: ${{ secrets.TOKEN_GIHUB }}
ref: ${{ inputs.target_branch }}
path: cloud-repo
- name: Update manifest
run: |
cd cloud-repo
sed -i "s/tag: .*/tag: ${{ steps.build.outputs.IMAGE_TAG }}/" k8s-argocd-helm/apps/${{ inputs.service }}/values.yaml
- name: Commit and push
run: |
cd cloud-repo
git config --local user.email "action@github.com"
git config --local user.name "GitHub Action"
git add k8s-argocd-helm/apps/${{ inputs.service }}/values.yaml
git commit -m "Deploy ${{ inputs.service }} from commit ${{ env.SHORT_HASH }}"
git push
```
- 추가로 참고해야 …
> fix: 임시로 manifest 수정하도록 수정

- .github/workflows/k8s-deploy-by-commit.yml
> hotfix: 오타 수정

- k8s-argocd-helm/argocd/templates/applications/apps/backend-application.yaml
- k8s-argocd-helm/argocd/templates/applications/apps/frontend-application.yaml
- k8s-argocd-helm/argocd/templates/applications/apps/kafka-application.yaml
- k8s-argocd-helm/argocd/templates/applications/apps/mysql-application.yaml
- k8s-argocd-helm/argocd/templates/applications/apps/redis-application.yaml
- k8s-argocd-helm/argocd/templates/applications/apps/signoz-application.yaml
- k8s-argocd-helm/argocd/templates/applications/infrastructure/alb-application.yaml
- k8s-argocd-helm/argocd/templates/applications/infrastructure/network-application.yaml
- k8s-argocd-helm/argocd/templates/applications/infrastructure/reloader-application.yaml
- k8s-argocd-helm/argocd/templates/applications/infrastructure/secrets-application.yaml
- k8s-argocd-helm/argocd/templates/projects/tuning-project-dev.yaml
- ArgoCD application 및 project의 Hook 우선순위 설정
- "helm.sh/hook-weight" 설정 추가
> fix: ArgoCD application 및 project의 Hook 우선순위 설정

- terraform/gcp/modules/external-https-lb/main.tf
```
lifecycle {
create_before_destroy = true
replace_triggered_by = [google_compute_target_http_proxy.this]
}
```
> fix: replace 트리거 추가

- .github/workflows/deploy-ai.yml
> hotfix: deploy 부분 누락 수정

- k8s-argocd-helm/apps/signoz/Chart.yaml
- k8s-argocd-helm/apps/signoz/values.yaml
- k8s-argocd-helm/argocd/templates/applications/apps/signoz-application.yaml
- signoz infra-metrics 삭제
- 리소스 정보도 가져올 수 있도록 설정
> fix: signoz 설정 변경

- k8s-argocd-helm/apps/signoz/templates/collector-egress-np.yaml
> fix: 네트워크 템플릿 추가

- .github/workflows/k8s-deploy-by-commit.yml
> hotfix:브렌치 / 를 - 로 치환

- k8s-argocd-helm/apps/monitoring/templates/prometheus.yaml
> fix: CRD 문제 해결

- k8s-argocd-helm/Chart.yaml
- k8s-argocd-helm/apps/frontend/templates/service.yaml
- k8s-argocd-helm/apps/monitoring/templates/custom-dashboard.yaml
- k8s-argocd-helm/apps/monitoring/templates/prometheus.yaml
- k8s-argocd-helm/apps/monitoring/values-prod.yaml
- k8s-argocd-helm/apps/monitoring/values-stage.yaml
- k8s-argocd-helm/argocd/values.yaml
- k8s-argocd-helm/aws-iam/karpenter-controller-policy.json
- monitoring
- prometheus
- grafana
- loki
- loki를 활용한 로그 대시보드
- k8s cluster 모니터링
> feat: prometheus , loki, promtail, grafana 최종 적용

- k8s-argocd-helm/apps/monitoring/templates/prometheus.yaml
> hotfix: crd가 설치 되지 않는문제 해결

- k8s-argocd-helm/apps/monitoring/templates/loki.yaml
- k8s-argocd-helm/apps/monitoring/templates/prometheus-crd-job.yaml
- k8s-argocd-helm/apps/monitoring/templates/prometheus.yaml
- k8s-argocd-helm/apps/monitoring/templates/promtail.yaml
> fix: CRD job으로 등록하여 따로 설치

- k8s-argocd-helm/apps/monitoring/templates/prometheus-crd-job.yaml
> hotfix: wave 0으로 통일

- k8s-argocd-helm/apps/monitoring/templates/prometheus-crd.yaml
- k8s-argocd-helm/apps/monitoring/values-stage.yaml
> fix: prometheus 리소스 표기 수정

- k8s-argocd-helm/apps/monitoring/templates/loki.yaml
- k8s-argocd-helm/apps/monitoring/templates/prometheus-crd.yaml
- k8s-argocd-helm/apps/monitoring/templates/prometheus.yaml
- k8s-argocd-helm/apps/monitoring/templates/promtail.yaml
- k8s-argocd-helm/apps/monitoring/values-stage.yaml
> fix: namspace를 argocd로 통일

- k8s-argocd-helm/apps/backend/templates/deployment.yaml
> fix: 환경변수 부분 롤백

- .gitignore
- k8s-argocd-helm/apps/backend/templates/deployment.yaml
- k8s-argocd-helm/apps/monitoring/values-prod.yaml
- k8s-argocd-helm/apps/monitoring/values-stage.yaml
- k8s-argocd-helm/infrastructure/secrets/templates/externalsecret-fcm.yaml
- otel 볼륨 누락 부분 수정
- fcm 전용 secret 생성
- loki values 수정
> fix: fcm 트러블 슈팅, loki 수정

- .github/workflows/k8s-deploy-by-commit.yml
- k8s-argocd-helm/apps/monitoring/values-stage.yaml
fix: deploy-by-commit 매니패스트 수정 x , loki 기본 볼륨 설정
> fix: deploy-by-commit 매니패스트 수정 x , loki 기본 볼륨 설정

- k8s-argocd-helm/apps/backend/values-stage.yaml
> fix: k8s-develop-latest

- .github/workflows/deploy-backend.yml
- .github/workflows/stop-gcp-instance.yml
- deploy_backend 부하테스트 추가
- stop 추가
> feat: 부하테스트 서버 deploy, stop 추가

- .github/workflows/deploy-backend.yml
> fix: 메시지 부분 수정

- k8s-argocd-helm/infrastructure/karpenter/provisioner-general.yaml
- karpenter의 provisioner 설정에 spot 인스턴스 추가
- karpenter의 provisioner 설정에 spot 인스턴스 추가
> feat: karpenter의 provisioner 설정에 spot 인스턴스 추가

- k8s-argocd-helm/apps/monitoring/values-prod.yaml
- k8s-argocd-helm/apps/monitoring/values-stage.yaml
- monitoring loki의 syncout 해결
- helm chart의 default 설정을 명시적으로 추가
> fix: monitoring loki의 syncout 해결

- k8s-argocd-helm/apps/monitoring/templates/loki.yaml
- k8s-argocd-helm/apps/monitoring/values-prod.yaml
- k8s-argocd-helm/apps/monitoring/values-stage.yaml
- loki syncout 제거
- "installCRDs: true" 제거
> fix: loki syncout 제거

- .github/workflows/deploy-backend.yml
- .github/workflows/deploy-kafka.yml
- deploy_backend 실행시 kafka도 실행 되도록 수정
> fix: backend_deploy에도 붙이기

- .github/workflows/deploy-backend.yml
> hotfix: bugfix

- .github/workflows/stop-gcp-instance.yml
hotfix: stop-gcp-instance 문법 오류
> hotfix: stop-gcp-instance 문법 오류

- k8s-argocd-helm/apps/monitoring/values-prod.yaml
- k8s-argocd-helm/apps/monitoring/values-stage.yaml
- RBAC가 클러스터가 아닌 네임스페이스에 종속되도록 설정
- RBAC가 클러스터가 아닌 네임스페이스에 종속되도록 설정
> fix: RBAC가 클러스터가 아닌 네임스페이스에 종속되도록 설정

- k8s-argocd-helm/apps/monitoring/templates/promtail.yaml
- 리소스의 부족으로 데몬셋이 설치되지 않는 오류 수정
- sync 우선순위를 2->0으로 높게 조정
> fix: 리소스의 부족으로 데몬셋이 설치되지 않는 오류 수정

- k8s-argocd-helm/infrastructure/alb/templates/ingress.yaml
> fix: alb timeout 값 수정

- k8s-argocd-helm/infrastructure/alb/templates/ingress.yaml
- prod와 stage의 alb가 합쳐지는 오류 수정
- prod와 stage의 alb가 합쳐지는 오류 수정
> fix: prod와 stage의 alb가 합쳐지는 오류 수정

- k8s-argocd-helm/infrastructure/alb/templates/ingress.yaml
> fix: ingress의 alb group 오타 수정

- k8s-argocd-helm/infrastructure/alb/templates/ingress.yaml
> fix: 웹소켓 헬스체크 실패도 통신이 되지 않는 문제

- .github/workflows/deploy-ai.yml
- .github/workflows/stop-gcp-instance.yml
- ai/ecosystem.config.js
fix: app.hertz-deploy , stop instance bugfix
> fix: app.hertz-deploy , stop instance bugfix

- .github/workflows/deploy-ai.yml
> fix: 디스코드 메시지를 서비스 별로 구분하여 출력 하도록 수정

- .github/workflows/stop-gcp-instance.yml
hotfix: chat-report stop 오타 수정
> hotfix: chat-report stop 오타 수정

- k8s-argocd-helm/infrastructure/secrets/templates/externalsecret-nextjs.yaml
- k8s-argocd-helm/infrastructure/secrets/templates/externalsecret-springboot-fcm.yaml
- k8s-argocd-helm/infrastructure/secrets/templates/externalsecret-springboot.yaml
- SSM 잘못된 경로 수정
- values 값에서 가져오는 경로 수정
> fix: SSM 잘못된 경로 수정

- .github/workflows/stop-gcp-instance.yml
> fix: chat-report 테스트 인스턴스 종료 에러

- .github/workflows/stop-gcp-instance.yml
- AI 신고 서버 CI/CD 오류
- AI 신고 서버 CI/CD 오류
> fix: AI 신고 서버 CI/CD 오류

- .github/workflows/k8s-deploy-by-commit.yml
> refactor: fe 환경 변수 추가

- .github/workflows/k8s-deploy-by-commit.yml
- .github/workflows/k8s-deploy-by-image-tag.yml
- k8s-argocd-helm/argocd/templates/applications/stage/monitoring-application-stage.yaml
- 소스 브렌치에 따라 k8s-develop ,  k8s-main 으로 배포 가능 하도록 수정 
```
source_branch:
description: 'main/develop'
required: true
default: 'develop'
```
> refactor: 환경별 배포 가능
